# The .npz files generated by `interp_tasks_small_init_stim.py` take up a lot of memory because they
# are storing the state trajectories. Because I am not using this data I want to be able to delete it

import os
import numpy as np
import shutil

folder_path = "/Users/slibkind/Documents/data/sophie-nets/binary_inputs/data/basic/LeakyRNN/softplus/randgauss/1_tasks/256_n_rnn/lr7.0l2_w7.0_h7.0_sig_rec0.05_sig_x0.1_w_rec_coeff0.9_delaygo/0/interp_tasks_small_init_stim/delaygo_delaygo/tol_q_e_6.0"
temp_folder_path = "/Users/slibkind/Documents/data/sophie-nets/binary_inputs/data/basic/LeakyRNN/softplus/randgauss/1_tasks/256_n_rnn/lr7.0l2_w7.0_h7.0_sig_rec0.05_sig_x0.1_w_rec_coeff0.9_delaygo/0/interp_tasks_small_init_stim/delaygo_delaygo/tmp/tol_q_e_6.0"

# Create a temporary folder to save the modified files
os.makedirs(temp_folder_path, exist_ok=True)

# Loop through each .npz file in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith(".npz"):
        file_path = os.path.join(folder_path, file_name)
        temp_file_path = os.path.join(temp_folder_path, file_name)

        # Load the .npz file
        data = np.load(file_path)

        # Create a new dictionary for the modified data
        modified_data = {key: value for key, value in data.items() if key != "state_traj"}

        # Save the modified .npz file to the temporary folder
        np.savez(temp_file_path, **modified_data)

        print(f"Array 'state_traj' removed from {file_name}. Modified file saved to temporary folder.")

# Replace the original files with the modified files from the temporary folder
for file_name in os.listdir(temp_folder_path):
    if file_name.endswith(".npz"):
        temp_file_path = os.path.join(temp_folder_path, file_name)
        original_file_path = os.path.join(folder_path, file_name)

        # Replace the original file with the modified file
        shutil.move(temp_file_path, original_file_path)

# Remove the temporary folder
shutil.rmtree(temp_folder_path)

print("Modification complete. Original files overwritten with the modified files.")
